on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          os: ubuntu-latest
          version: 10.0.0
      - name: AIO Version Lib
        run: aio -v
      - name: Build
        env:
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ubuntu-latest
          command: build